# Generated by Django 4.2.7 on 2024-04-07 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_orgform'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgform',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orgform',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
