# Generated by Django 4.2.7 on 2024-05-12 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_orgform_created_orgform_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgform',
            options={'verbose_name': 'форма организатора', 'verbose_name_plural': 'формы организаторов'},
        ),
        migrations.AlterField(
            model_name='orgform',
            name='last_surname',
            field=models.CharField(max_length=20, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='name',
            field=models.CharField(max_length=20, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='организация'),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirm'), ('canceled', 'Canceled')], default='pending', max_length=12, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='surname',
            field=models.CharField(max_length=20, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_form', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='users_photos', verbose_name='аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, verbose_name='краткая информация'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ru', 'Russian')], default='Russian', max_length=2, verbose_name='язык'),
        ),
        migrations.AlterField(
            model_name='user',
            name='superhost',
            field=models.BooleanField(default=False, verbose_name='организатор'),
        ),
    ]
