# Generated by Django 4.2.7 on 2024-03-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='events', to='events.tag'),
        ),
    ]
