# Generated by Django 4.2.7 on 2024-03-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventuserrating',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
