# Generated by Django 4.2.7 on 2024-04-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_event_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventuserrating',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
