# Generated by Django 4.2.7 on 2024-04-16 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_eventuserrating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventuserrating',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='events.event'),
        ),
    ]
